query GetCategories {
  categories {
    data {
      id
      attributes {
        name
        slug
        products {
          data {
            id
            attributes{
              name
              images{
                data {
                  id
                  attributes {
                    name
                    url
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
